version: '3'
services:
  db:
    build: ./api/db
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tinysis
    ports:
      - 3316:3306
    restart: always
    volumes:
      - tiny_ale_data:/var/lib/mysql
  web:
    build:
      context: ./api
      dockerfile: Dockerfile.development
    command: bash -c "rm -f tmp/pids/server.pid && rails s -b 0.0.0.0"
    volumes:
      - ./api:/api
    ports:
      - "3000:3000"
    environment:
      - TINYSIS_HOST=db
      - TINYSIS_DATABASE=tinysis
      - TINYSIS_USER=root
      - TINYSIS_PASSWORD=root
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - RAILS_ENV=development
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
  ux:
    build:
      context: ./ui
      dockerfile: Dockerfile
    volumes:
      - ./ui:/ui
      - /ui/node_modules
      - /ui/tmp
    command: npx ember serve --proxy=http://web:3000 --port=3001
    ports:
      - "3001:3001"
volumes:
  tiny_ale_data:
