default: &default
  adapter: 'mysql2'

development:
  <<: *default
  database: 'nova_development'
  username: 'nova_development'
  password: 'nova_development'
  host: 'localhost'

test:
  <<: *default
  database: 'nova_test'
  username: 'nova_test'
  password: 'nova_test'
  host: 'localhost'