default: &default
  adapter: 'mysql2'

development: &development
  <<: *default
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['DB_DATABASE'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>

test:
  <<: *default
  database: 'nova_test'
  username: 'nova_test'
  password: 'nova_test'

production:
  <<: *development
